name: CI Actividad 7

on:
  push:
    branches: [main]
    paths:
      - 'Backdoor/Actividad-07/**'
  pull_request:
    branches: [main]
    paths:
      - 'Backdoor/Actividad-07/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backdoor/Actividad-07  # Todas las rutas serán relativas aquí

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: flake8 src/ tests/
      - run: pytest --junitxml=reports/pytest-report.xml --cov=src --cov-report=html
      - run: behave -f junit -o reports/
      - uses: actions/upload-artifact@v3
        with:
          name: reportes-actividad-7
          path: Backdoor/Actividad-07/reports/