name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app/tests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL || 'https://sonarcloud.io' }}
        with:
          args: >
            -Dsonar.projectKey=junalchowdhurygomez_BackDoor
            -Dsonar.organization=junalchowdhurygomez
            -Dsonar.sources=app
            -Dsonar.python.version=3.11
            -Dsonar.python.coverage.reportPaths=app/coverage.xml
            -Dsonar.coverage.exclusions=app/tests/**,**/__init__.py
            -Dsonar.test.exclusions=app/tests/**
            -Dsonar.python.xunit.reportPath=app/tests/report.xml
            -Dsonar.verbose=true
            -Dsonar.scm.provider=git
            -Dsonar.cpd.exclusions=app/tests/**