name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app/tests

      - name: Set up Java for SonarCloud
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: junalchowdhurygomez_BackDoor
          SONAR_ORGANIZATION: junalchowdhurygomez
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL || 'https://sonarcloud.io' }}
        args: >
          -Dsonar.projectKey=JunalChowdhuryGomez_BackDoor
          -Dsonar.organization=junalchowdhurygomez
          -Dsonar.sources=app
          -Dsonar.python.version=3.11
          -Dsonar.coverage.exclusions=tests/**,**/__init__.py
          -Dsonar.test.exclusions=tests/**
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-
          
      - name: Run Security Scan
        run: bandit -r app