name: Python CI

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: Set up Java 17 for SonarQube
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app/tests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -X
            -Dsonar.projectKey=junalchowdhurygomez_BackDoor
            -Dsonar.organization=junalchowdhurygomez
            -Dsonar.sources=app
            -Dsonar.python.version=3.11
            -Dsonar.verbose=true